### ISSUE TITLE
Sublime Text 3 support

### ISSUE THREAD

**Issue by pensierinmusica** [hahiserw/AceJump#4]
Hi there! Great plugin  :)

Any plan to update the package with support for ST3?

Thanks. Cheers,

  Alex

**Comment by steven-pribilinskiy** [comment]
Subscribing to this request too

**Comment by hahiserw** [comment]
Whoa, I just noticed this.

I thought about rewriting AceJump completly some time ago, because I discovered a better way of handling keypresses. But I just left it because I didn't know someone is using it. I'll see what I can do.

I can update AceJump to make it work with ST3 for now if you want it that badly. But give me some time. I need to study now. :P

**Comment by pensierinmusica** [comment]
@hahiserw Sure, thanks!  :)

**Comment by hahiserw** [comment]
Ok, I used some tricks to make it work with ST3. I hope it works for you. :)
However it would be better to rewrite it...

**Comment by davidson16807** [comment]
I've installed this on ST3. So far working like a champ.

**Comment by pensierinmusica** [comment]
@hahiserw awesome thx!!  :)

Btw, are the modifiers still working?
